- ignore: {name: "Avoid lambda"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Redundant lambda"}
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Use <$"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use $>"}
- ignore: {name: "Use const"}
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use section"}
 - ignore {name: "Use tuple-section}"
- warn: {name: Redundant bracket due to operator fixities}
